fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "6.1.1"
  symlinks:
    aptly: "#{source_dir}"
